BudgetApplicationView/Models/HouseHolds.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BudgetApplicationView.Models
{
    public class HouseHolds
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CreatorId { get; set; }
        public virtual ApplicationUser Creator{ get; set; }

        public HouseHolds()
        {
            HouseHoldInvites = new HashSet<HouseHoldInvites>();
            Accounts = new HashSet<Accounts>();
            Categories = new HashSet<Categories>();
            HouseHoldUser = new HashSet<ApplicationUser>();
        }

        public virtual ICollection<HouseHoldInvites> HouseHoldInvites { get; set; }
        public virtual ICollection<Categories> Categories { get; set; }
        public virtual ICollection<Accounts> Accounts { get; set; }
        public virtual ICollection<ApplicationUser> HouseHoldUser { get; set; }
    }
}

BudgetApplicationView/Models/ViewUsersInHouseHoldViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BudgetApplicationView.Models
{
    public class ViewUsersInHouseHoldViewModel
    {
        public int Id { get; set; }
        public IList<string> Email { get; set; }
    }
}

BudgetApplicationView/Controllers/CategoryController.cs
using BudgetApplicationView.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace BudgetApplicationView.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Categories
        public ActionResult ViewCategories(int id)
        {
            var cookie = Request.Cookies["token"];
            if (cookie == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var accessToken = cookie.Value;
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
            var result =
               httpClient.GetAsync("http://localhost:54111/api/categories/View/" + id).Result;
            if (result.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var jsonString = result.Content.ReadAsStringAsync().Result;
                var houseHolds = JsonConvert
                   .DeserializeObject<List<CreateCategoryViewModel>>(jsonString);
                return View(houseHolds);
            }
            return View();
        }

        [HttpGet]
        public ActionResult CreateCategories()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateCategories(CreateCategoryViewModel model, int id)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var cookie = Request.Cookies["token"];
            if (cookie == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var accessToken = cookie.Value;
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);

            var parameters = new List<System.Collections.Generic.KeyValuePair<string, string>>();
            parameters.Add(new KeyValuePair<string, string>("Name", model.Name));
            parameters.Add(new KeyValuePair<string, string>("houseHoldId", model.Id.ToString()));

            var formEncodedValues = new FormUrlEncodedContent(parameters);

            var result =
               httpClient.PostAsync("http://localhost:54111/api/categories/PostCategories/", formEncodedValues).Result;

            if (result.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var jsonString = result.Content.ReadAsStringAsync().Result;
                var houseHolds = JsonConvert
                   .DeserializeObject<CreateCategoryViewModel>(jsonString);
                return View(houseHolds);
            }
            return View();
        }
    }
}

BudgetApplicationView/Controllers/HouseHoldsController.cs
using BudgetApplicationView.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace BudgetApplicationView.Controllers
{
    public class HouseHoldsController : Controller
    {
        public ActionResult Index()
        {
            var cookie = Request.Cookies["token"];
            if (cookie == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var accessToken = cookie.Value;
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
            var result =
               httpClient.GetAsync("http://localhost:54111/api/households/viewHouseHolds").Result;
            if (result.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var jsonString = result.Content.ReadAsStringAsync().Result;
                var houseHolds = JsonConvert
                   .DeserializeObject<List<ViewHouseHoldViewModel>>(jsonString);
                return View(houseHolds);
            }
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateHouseHoldViewModel model)
        {
            var cookie = Request.Cookies["token"];
            if (cookie == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var accessToken = cookie.Value;
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
            
            var parameters = new List<System.Collections.Generic.KeyValuePair<string, string>>();
            parameters.Add(new KeyValuePair<string, string>("Name", model.Name));

            var formEncodedValues = new FormUrlEncodedContent(parameters);

            var result =
               httpClient.PostAsync("http://localhost:54111/api/households/PostHouseHolds", formEncodedValues).Result;
            
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(EditHouseHoldViewModel model, int id)
        {
            var cookie = Request.Cookies["token"];
            if (cookie == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var accessToken = cookie.Value;
            var CreatorId = User.Identity.GetUserId();
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
            var parameters = new List<System.Collections.Generic.KeyValuePair<string, string>>();
            parameters.Add(new KeyValuePair<string, string>("Name", model.Name));
            //parameters.Add(new KeyValuePair<string, string>("HouseHoldId", model.HouseHoldId));

            var formEncodedValues = new FormUrlEncodedContent(parameters);
            var result =
               httpClient.PutAsync("http://localhost:54111/api/households/PutHouseHolds/" + id, formEncodedValues).Result;

            if (result.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var jsonString = result.Content.ReadAsStringAsync().Result;
                var houseHolds = JsonConvert
                   .DeserializeObject<HouseHolds>(jsonString);
                return View(houseHolds);
            }
            return View();
        }

        public ActionResult ViewUsersInHouseHold(ViewUsersInHouseHoldViewModel model, int id)
        {
            var cookie = Request.Cookies["token"];
            if (cookie == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var accessToken = cookie.Value;
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
            var result =
               httpClient.GetAsync("http://localhost:54111/api/households/ViewHouseHoldPerUser/"+ id).Result;
            if (result.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var jsonString = result.Content.ReadAsStringAsync().Result;
                var houseHolds = JsonConvert
                   .DeserializeObject<List<ViewUsersInHouseHoldViewModel>>(jsonString);
                return View(houseHolds);
            }
            return View();
        }

        [HttpGet]
        public ActionResult Invite(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Invite(int id, InviteUserViewModel model)
        {
            var cookie = Request.Cookies["token"];
            if (cookie == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var accessToken = cookie.Value;
            var CreatorId = User.Identity.GetUserId();
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
            var parameters = new List<System.Collections.Generic.KeyValuePair<string, string>>();
            parameters.Add(new KeyValuePair<string, string>("Email", model.Email));
            parameters.Add(new KeyValuePair<string, string>("Id", model.Id));


            var formEncodedValues = new FormUrlEncodedContent(parameters);
            var result =
               httpClient.PostAsync("http://localhost:54111/api/households/Invite/" + id, formEncodedValues).Result;

            if (result.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var jsonString = result.Content.ReadAsStringAsync().Result;
                var houseHolds = JsonConvert
                   .DeserializeObject<InviteUserViewModel>(jsonString);
                return View(houseHolds);
            }
            return View();
        }

        [HttpPost]
        public ActionResult Join(int id)
        {
            var cookie = Request.Cookies["token"];
            if (cookie == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var accessToken = cookie.Value;
            var CreatorId = User.Identity.GetUserId();
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
            var parameters = new List<System.Collections.Generic.KeyValuePair<string, string>>();
            //parameters.Add(new KeyValuePair<string, string>("HouseHoldId", model.Id));


            var formEncodedValues = new FormUrlEncodedContent(parameters);
            var result =
               httpClient.PostAsync("http://localhost:54111/api/households/Invite/" + id, formEncodedValues).Result;

            if (result.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var jsonString = result.Content.ReadAsStringAsync().Result;
                var houseHolds = JsonConvert
                   .DeserializeObject<InviteUserViewModel>(jsonString);
                return View(houseHolds);
            }
            return View();
        }

        

        

        

    }
}

BudgetApplicationView/Views/HouseHolds/Create.cshtml
@model BudgetApplicationView.Models.HouseHolds
@{
    ViewBag.Title = "Create";
}

<h2>Create HouseHolds</h2>


@using (Html.BeginForm("Create", "HouseHolds", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Back to List", "Index")

</div>

BudgetApplicationView/Views/HouseHolds/Edit.cshtml
@model BudgetApplicationView.Models.HouseHolds
@{
    ViewBag.Title = "Edit";
}

<h2>Edit HouseHolds</h2>


@using (Html.BeginForm("Edit", "HouseHolds", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")

</div>

BudgetApplicationView/Views/HouseHolds/Index.cshtml
@model List<BudgetApplicationView.Models.ViewHouseHoldViewModel>
@{
    ViewBag.Title = "Index";
}
<h2>Households</h2>
<p>Find below the list of households that you have created</p>
@if (Model == null || !Model.Any())
{
    <p>You haven't created any households</p>
}
else
{
    <table>
        <thead>
            <tr>
                Name
            </tr>
            <tr>
                Number of Members
            </tr>
        </thead>
        <tbody>
            @foreach (var household in Model)
            {
                <tr>
                    <td>
                        @household.Name
                    </td>
                    <td>
                        @household.NumberOfUsers
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = household.Id }) |
                        @Html.ActionLink("View Members", "ViewUsersInHouseHold", new { id = household.Id })|
                        @Html.ActionLink("Invite", "Invite", new { id = household.Id })|
                        @Html.ActionLink("Categories", "CreateCategories", "Category", new { id = household.Id }, null) |
                        @Html.ActionLink("View Categories", "ViewCategories", "Category", new { id = household.Id }, null) |
                        @Html.ActionLink("Accounts", "CreateAccounts", "Accounts", new { id = household.Id }, null)|
                        @Html.ActionLink("View accounts", "ViewAccounts", "Accounts", new { id = household.Id }, null) |
                        @Html.ActionLink("Transactions", "CreateTransactions", "Transaction", new { id = household.Id }, null)|

                    </td>
                </tr>
            }
        </tbody>
    </table>
}

BudgetApplicationView/Views/HouseHolds/Invite.cshtml
@model BudgetApplicationView.Models.InviteUserViewModel
@{
    ViewBag.Title = "Invite";
}

<h2>Invite HouseHold Users</h2>


@using (Html.BeginForm("Invite", "HouseHolds", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Invite" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")

</div>

BudgetApplicationView/Views/HouseHolds/ViewUsersInHouseHold.cshtml
@model List<BudgetApplicationView.Models.ViewUsersInHouseHoldViewModel>
@{
    ViewBag.Title = "Members In HouseHold";
}
<h2>Users In HouseHold</h2>
<p>Find below the list of members in households that you have created</p>
@if (Model == null || !Model.Any())
{
    <p>You haven't created any households</p>
}
else
{
    <table>
        <thead>

            <tr>
                Email
            </tr>
        </thead>
        <tbody>
            @foreach (var household in Model)
            {
            <tr>
                <td>
                    @household.Email
                </td>
                <td>
                    @Html.ActionLink("Join HouseHold", "Join", new { id = household.Id }) |
                </td>
            </tr>
            }
        </tbody>
    </table>
}